env:
  global:
    - DATABASE_TEST=postgres://postgres@localhost:5000/questioner
language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - psql -c 'create database questioner;' -U postgres
  - NODE_ENV=test npm run
script:
  - npm test
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
 

               

