language: node_js
node_js:
  - "stable"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  services:
  - postgresql
script:
  - npm test
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
 

               

